apiVersion: v1                    # API version
kind: Service                     # Type of kubernetes resource
metadata:
  name: employee-service-postgres   # Name of the service
  labels:                         # Labels that will be applied to the service
    app: employee-service
spec:
  ports:
    - port: 5432
  selector:                       # Selects any Pod with labels `app=employee-service,tier=postgres`
    app: employee-service
    tier: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment                    # Type of the kubernetes resource
metadata:
  name: employee-service-postgres-deployment           # Name of the deployment
  labels:                           # Labels applied to this deployment
    app: employee-service
spec:
  selector:
    matchLabels:                    # This deployment applies to the Pods matching the specified labels
      app: employee-service
      tier: postgres
  strategy:
    type: Recreate
  template:                         # Template for the Pods in this deployment
    metadata:
      labels:                       # Labels to be applied to the Pods in this deployment
        app: employee-service
        tier: postgres
    spec:                           # The spec for the containers that will be run inside the Pods in this deployment
      containers:
        - image: postgres                # The container image
          name: postgres
          env:                        # Environment variables passed to the container
            - name: POSTGRES_PASSWORD
              value: "abc123"           # Read environment variables from kubernetes secrets
            - name: POSTGRES_DB
              value: "employees"
          ports:
            - containerPort: 5432       # The port that the container exposes
              name: postgres
---
apiVersion: apps/v1           # API version
kind: Deployment              # Type of kubernetes resource
metadata:
  name: employee-service-server-deployment    # Name of the deployment
  labels:                     # Labels that will be applied to this deployment
    app: employee-service-server
spec:
  replicas: 1                 # No. of replicas/pods to run in this deployment
  selector:
    matchLabels:              # The deployment applies to any pods mayching the specified labels
      app: employee-service-server
  template:                   # Template for creating the pods in this deployment
    metadata:
      labels:                 # Labels that will be applied to each Pod in this deployment
        app: employee-service-server
    spec:                     # Spec for the containers that will be run in the Pods
      containers:
        - name: employee-service-server
          image: goetsie/employee-service
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8051 # The port that the container exposes
          resources:
            limits:
              cpu: 0.2
              memory: "200Mi"
          env:                    # Environment variables supplied to the Pod
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "abc123"
            - name: POSTGRES_DB_HOST
              value: "employee-service-postgres"
---
apiVersion: v1                      # API version
kind: Service                       # Type of the kubernetes resource
metadata:
  name: employee-service-server    # Name of the service
  labels:                           # Labels that will be applied to this service
    app: employee-service-server
spec:
  type: NodePort                    # The service will be exposed by opening a Port on each node and proxying it. Allowing connections from outside the cluster
  selector:
    app: employee-service-server   # The service exposes Pods with label `app=employee-service-server`
  ports:                            # Forward incoming connections on port 8080 to the target port 8051
    - name: http
      port: 8051
      targetPort: 8051